name: Run Rest Assured API Tests

on:
  push:
    branches:
      - master

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Maven
        run: sudo apt-get install -y maven

      - name: Run API Tests with Maven
        run: mvn test
